name: CI

on:
  push:
    paths-ignore:
    - '*.md'
    - '*.org'
  pull_request:
    paths-ignore:
    - '*.md'
    - '*.org'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
        include:
          - emacs_version: 24.1
            lint_ignore: 1
          - emacs_version: 24.2
            lint_ignore: 1
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Run tests
      run: './run-tests.sh'
